services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URLS=http://llama-server-qwen2_5-coder-3b-instruct-q4_k_m:8080/v1;http://llama-server-qwen2_5-coder-7b-instruct-q4_k_m:8080/v1
      - OPENAI_API_KEYS=dummy
    volumes:
      - open-webui_data:/app/backend/data
    networks:
      - ai-network

networks:
  ai-network:
    external: true

volumes:
  open-webui_data:
