name: llama-qwen3-6-35b-a3b

services:
  llama-server:
    image: llama-server:gtx1060
    container_name: llama-server
    labels:
      - "llm.model=qwen36-35b-a3b"
    restart: unless-stopped
    ipc: host
    ports:
      - "7000:8080"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    tmpfs:
      - /usr/local/cuda/compat
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./models:/models
    command:
      - "-m"
      - "/models/Qwen3.6-35B-A3B-UD-Q4_K_M.gguf"
      - "--alias"
      - "local-model"
      - "-c"
      - "131072"
      - "-ngl"
      - "999"
      - "--n-cpu-moe"
      - "999"
      - "-np"
      - "1"
      - "-fa"
      - "auto"
      - "-t"
      - "4"
      - "--temperature"
      - "0.2"
      - "-ctk"
      - "q8_0"         # 8-bit Key cache quantization
      - "-ctv"
      - "q8_0"         # 8-bit Value cache quantization
      - "--jinja"
      - "--chat-template-file"
      - "/models/Qwen3.6-35B-A3B-UD-Q4_K_M.jinja"
      - "--load-mode"
      - "mlock"
      - "--reasoning-preserve"
      - "-lv"
      - "3"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]
    networks:
      - ai-network

networks:
  ai-network:
    external: true
